### ISSUE TITLE
Hyperlinks inside a package's tutorial lead to main page

### ISSUE THREAD

**Issue by fersantxez** [dcos-labs/dcos-universe-browser#1] opened 2016-12-17 01:19 UTC
Browsing a package's tutorial:
https://universe.serv.sh/#/package/ceph/docs

the links inside the tutorial lead to the main page instead of the document's content. For example, the link to the "Use Ceph" section leads to:
https://universe.serv.sh/#use-ceph

**Comment by tobilg** [comment] 2016-12-18 14:32
Thanks for reporting, I'll have a look.

**Comment by tobilg** [comment] 2016-12-19 10:30
This is (kind of) fixed, in the way that the anchor links are now referring to the correct page. There is still a problem though in Angular not scrolling to the actual anchors. This seems to be caused by the async loading of the example resources (after the page itself is loaded).

Closing this as of #2.

**Closed as completed by tobilg** 2016-12-19 10:30 UTC

**Comment by fersantxez** [comment] 2016-12-21 04:22
I am seeing that the internal links now take me to the top of the page instead of where the link is intended to. Is there any way to fix that? Thanks!

**Comment by tobilg** [comment] 2016-12-21 08:15
@fernandosanchezmunoz What browser are you testing with? In Chrome it doesn't scroll at all, this is a known issue as of #2. What was fixed is that it doesn't redirect to a wrong page anymore.

The scroll behavior is probably not triggered correctly because the page content is loaded asynchronously after the route change. Currently I'm investigating a fix and once I have it fix it in #2.

**Comment by fersantxez** [comment] 2016-12-21 15:46
oh thanks @tobilg. I'm testing with Chrome on OSX. Also tested with Safari and Firefox. Indeed any link points now to the top of the page. Good to know you're tracking that already, thanks!!
